In [11]:
import numpy as np

In [33]:
it = [3,6,7,11]
n = np.array(it)
print(n)
type(n)

[ 3  6  7 11]


numpy.ndarray

In [24]:
twod = np.array([[1,2],[3,4],5])

twod


array([list([1, 2]), list([3, 4]), 5], dtype=object)

In [38]:
twod = np.array([[1,2],[3,4]])

print(twod.shape)
print(twod.size)
twod

(2, 2)
4


array([[1, 2],
       [3, 4]])

In [27]:
y= np.array([2,5,6,"77"])
y

array(['2', '5', '6', '77'], dtype='<U11')

In [34]:
n.shape

(4,)

In [37]:
n.size

4

In [43]:
list(range(9,16,2))
#start,end-exclusive,jumping value
#normal range in python


[9, 11, 13, 15]

In [46]:
np.arange(0,3)

array([0, 1, 2])

In [64]:
np.arange(7,15)

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
np.array(range(2,10))

array([2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr1 = np.arange(40) 

In [76]:
arr2 = arr1.reshape(8,5)

In [77]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [78]:
arr1[0]=1000
arr1

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39])

In [79]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

True